### PR TITLE
feat: Add support for "IONOS by 1&1"

### PR DESCRIPTION
**Pull request by sc0ttes**

### CODE REVIEW

**Comment by eliottvincent** [comment]
Hey! Thanks for your contribution. Can you provide me the raw source of an email forwarded from 1&1 Webmail?

**Comment by sc0ttes** [comment]
https://gist.github.com/sc0ttes/1dac32677421bdd03aa403d4186df791

**Comment by eliottvincent** [comment]
Thanks a lot, last thing I'd like to see, if possible, is an example of an email with multiple CCs addresses inside. Still as a raw source. Thanks in advance!

**Comment by eliottvincent** [comment]
By the way, I have released [v1.3.0](https://www.npmjs.com/package/email-forward-parser/v/1.3.0) which contains the support for IONOS.

**Comment by sc0ttes** [comment]
I think the headers may be a tiny bit wonky since I'm sending from myself to aliases of myself but hope this helps: https://gist.github.com/sc0ttes/4a3f1aed6a804aa7fda5c01ece49405c

**Comment by sc0ttes** [comment]
I unfortunately don't have time right now but can try to do some testing and fill out the rest of your table in the README for IONOS sometime in the near future. If you're actually able to create a ticket and assign it to me on GitHub, that would be a great reminder.

**Comment by eliottvincent** [comment]
Thanks! About the CC thing, what I wanted is an email with CC inside, being forwarded. So, CC in the original email, not the parent email. This is just to see the format, so that I can cover more test cases.

**Comment by eliottvincent** [comment]
> I unfortunately don't have time right now but can try to do some testing and fill out the rest of your table in the README for IONOS sometime in the near future. If you're actually able to create a ticket and assign it to me on GitHub, that would be a great reminder.

I have created this issue: https://github.com/crisp-oss/email-forward-parser/issues/9

**Pull request merged**
